extends: default

ignore: |
  .venv/
  .git/
  tests/cassettes/

rules:
  line-length:
    max: 200
  truthy:
    check-keys: false
  document-start: disable
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1
  indentation: disable
